project_id = "ctoaskhjiqlwdnyflymw"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false

[functions.notify-new-booking]
verify_jwt = false

[functions.manage-admins]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-square-terminal-checkout]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[functions.send-email-resend]
verify_jwt = false